# Generated by Django 3.2 on 2023-02-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_room_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='receiver',
            field=models.CharField(default='null', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='sender',
            field=models.CharField(default='null', max_length=256),
            preserve_default=False,
        ),
    ]
