# Generated by Django 3.2 on 2023-02-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20230201_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
