# Generated by Django 3.2 on 2023-02-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_room_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSeenMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=256)),
                ('receiver', models.CharField(max_length=256)),
                ('message_status', models.CharField(choices=[('SINGLE_TICK', 'ST'), ('DOUBLE_TICK', 'DT'), ('DOUBLE_BLUE_TICK', 'DBT'), ('NOT_DELIVERED', 'ND')], default='ST', max_length=20)),
                ('image_link', models.CharField(max_length=256)),
                ('opening_count', models.IntegerField()),
                ('sender_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
