# Generated by Django 3.2 on 2023-02-09 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_messageseenmetric_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageseenmetric',
            name='message_seen_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messageseenmetric',
            name='message_seen_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
