# Generated by Django 3.2 on 2023-02-09 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20230210_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageseenmetric',
            name='message_seen_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
